<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ATMECSINLT-647" name="com.learning.testcases.BankManagerLoginTest" tests="1" failures="1" timestamp="2020-12-31T16:36:08 IST" time="5.138" errors="0">
  <testcase name="bankManagerLoginTest" time="5.138" classname="com.learning.testcases.BankManagerLoginTest">
    <failure type="java.lang.AssertionError" message="Bank Manager Login failed">
      <![CDATA[java.lang.AssertionError: Bank Manager Login failed
at org.testng.Assert.fail(Assert.java:99)
at com.learning.testcases.BankManagerLoginTest.bankManagerLoginTest(BankManagerLoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- bankManagerLoginTest -->
  <system-out>
<br>Verification failure : expected [Protractor practice website - Banking App] but found [Title]<br> <a target="_blank" href=Thu_Dec_31_16_35_25_IST_2020.jpg><img src=Thu_Dec_31_16_35_25_IST_2020.jpg height=200 width=200></img></a> <br> <br> Reporter.log() - Login Test successfully executed Capturing Screenshot....... <a target="_blank" href=Thu_Dec_31_16_35_29_IST_2020.jpg>Screenshot in new Window</a> <br> <a target="_blank" href=Thu_Dec_31_16_35_29_IST_2020.jpg><img height=200 width=200 src=Thu_Dec_31_16_35_29_IST_2020.jpg>  </system-out>
</testsuite> <!-- com.learning.testcases.BankManagerLoginTest -->
